services:

  backend:
    image: hydroshieldmkii/guardian-backend:${VERSION:-latest}
    container_name: guardian-backend
    environment:
      NODE_ENV: production
      DATABASE_PATH: /app/data/plex-guard.db
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

  frontend:
    image: hydroshieldmkii/guardian-frontend:${VERSION:-latest}
    container_name: guardian-frontend
    ports:
      - "${PLEXGUARD_FRONTEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      # optional variable to specifically set internal link to backend
      # BACKEND_URL: http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
    driver: local
